version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: clients
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/app
